# Generated by Django 3.0.3 on 2020-11-02 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applynumber', models.CharField(max_length=4)),
                ('rankboard', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
