# Generated by Django 3.0.3 on 2020-11-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='rankboard',
        ),
    ]
