# Generated by Django 3.1.3 on 2020-11-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_nextenrolltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextenrolltime',
            old_name='nextEnrollTime',
            new_name='EnrollTime',
        ),
        migrations.AddField(
            model_name='nextenrolltime',
            name='kind',
            field=models.CharField(choices=[('P', 'Past'), ('N', 'Now')], default='B', max_length=1),
        ),
    ]
